### ISSUE TITLE
I want to add SignUp backend

### ISSUE THREAD

**Issue by Anushika09** [Anushika09/SignUp#3]
I want to add signup backend using passportjs

**Comment by Jash271** [comment]
Hey I'd like to look into this issue

**Comment by Vedant1202** [comment]
Hi, @Anushika09, I would like to work on this. Could you tell me more of how you want the backend to be setup? Mainly in terms of what data of users would you like to store?

**Comment by Anushika09** [comment]
> Hi, @Anushika09, I would like to work on this. Could you tell me more of how you want the backend to be setup? Mainly in terms of what data of users would you like to store?

Actually other person have already made a pull request...you can  optimize that code

**Comment by Vedant1202** [comment]
Okay
